<?php
/*
 * Copyright (c) 2012 David Pesta, https://github.com/DavidPesta/JSComponent
 * This template file is licensed under a MODIFIED MIT License:
 * The intent of this template file is for you to remove this license and replace it with your own.
 * This applies only to template files in this project. All MIT liability disclaimers remain in effect.
 * David Pesta relinquishes copyright over just this file the instant you modify it for your own project.
 */
?>

<div class="AjaxTemplate">
	<!-- HTML structure for this JSComponent !-->
</div>
