<?php
/*
* Copyright (c) 2012-2013 David Pesta, https://github.com/DavidPesta/JSComponent
* This file is licensed under the MIT License.
* You should have received a copy of the MIT License along with this program.
* If not, see http://www.opensource.org/licenses/mit-license.php
*/
?>

<div class="Page3">
	<div>--- Page 3 Start ---</div>
	<div><input type="button" class="changePage" value="Back to Page 1"></div>
	<div>--- Page 3 End ---</div>
</div>
