<?php
/*
* Copyright (c) 2012-2013 David Pesta, https://github.com/DavidPesta/JSComponent
* This file is licensed under the MIT License.
* You should have received a copy of the MIT License along with this program.
* If not, see http://www.opensource.org/licenses/mit-license.php
*/
?>

<div class="Component2">
	<div>Component2: A control that sits inside of the Component1 panel and contains yet another component</div>
	<div class="component3"></div>
	<div>End of Component2</div>
</div>
