<?php
/*
* Copyright (c) 2012-2013 David Pesta, https://github.com/DavidPesta/JSComponent
* This file is licensed under the MIT License.
* You should have received a copy of the MIT License along with this program.
* If not, see http://www.opensource.org/licenses/mit-license.php
*/
?>

<div class="Component3">
	<div>Component3: Some sort of simple widget or set of widgets that accomplish some purpose</div>
	<div>
		<input type="button" class="component3Button" value="Cascading Parent Actions">
		<input type="button" class="component3AjaxButton" value="Component 3 Ajax">
	</div>
	<div>End of Component3</div>
</div>
