<?php
/*
* Copyright (c) 2012-2013 David Pesta, https://github.com/DavidPesta/JSComponent
* This file is licensed under the MIT License.
* You should have received a copy of the MIT License along with this program.
* If not, see http://www.opensource.org/licenses/mit-license.php
*/
?>

<div class="Page1">
	<div>--- Page 1 Start ---</div>
	<div><input type="button" class="changePage" value="Go to Page 2"></div>
	<div>--- Page 1 End ---</div>
</div>
