<?php
/*
* Copyright (c) 2012-2013 David Pesta, https://github.com/DavidPesta/JSComponent
* This file is licensed under the MIT License.
* You should have received a copy of the MIT License along with this program.
* If not, see http://www.opensource.org/licenses/mit-license.php
*/
?>

<div class="Component3">
	<div style="margin: 16px;">
		<div style="border: 1px solid #0FF; width: 536px;">
			<div style="margin: 16px;">
				<input type="button" class="component3Button" value="Component 3's Method">
				<input type="button" class="component3AjaxButton" value="Component 3 Ajax">
			</div>
		</div>
	</div>
</div>
