<?php
/*
* Copyright (c) 2012-2013 David Pesta, https://github.com/DavidPesta/JSComponent
* This file is licensed under the MIT License.
* You should have received a copy of the MIT License along with this program.
* If not, see http://www.opensource.org/licenses/mit-license.php
*/
?>

<div class="SimpleExample">
	<div class="firstState">
		firstState Message
	</div>
	<div class="secondState">
		secondState Message
	</div>
	<div>
		<input type="button" class="toggleState" value="Toggle State">
	</div>
</div>
