<?php
/*
* Copyright (c) 2012-2013 David Pesta, https://github.com/DavidPesta/JSComponent
* This file is licensed under the MIT License.
* You should have received a copy of the MIT License along with this program.
* If not, see http://www.opensource.org/licenses/mit-license.php
*/
?>

<div class="Component1">
	<div style="border: 1px solid #000; width: 600px;">
		<div class="component2Container"></div>
		<div style="margin: 16px;"><input type="button" class="addComponent2" value="Add A Component 2"></div>
	</div>
</div>
